project_id = "cztfufjkowkdnaqmmiqq"

[functions.admin-data-agent]
verify_jwt = false

[functions.export-import-job]
verify_jwt = false

[functions.admin-create-users]
verify_jwt = false

[functions.admin-apply-setup]
verify_jwt = false

[functions.sinistralidade-pdf-agent]
verify_jwt = false

[functions.ai-alertas-recomendacoes]
verify_jwt = false
